/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'customerPhone' : string,
  'customerAddress' : string,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem { 'productId' : bigint, 'quantity' : bigint }
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'priceCents' : bigint,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [string, string, bigint, string, string, boolean],
    bigint
  >,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deploy' : ActorMethod<[], undefined>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'placeOrder' : ActorMethod<
    [string, string, string, Array<OrderItem>, bigint],
    bigint
  >,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, bigint, string, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];